=== SuyashC1000/openmock/public/schema/userCacheSchema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/UserCache",
  "definitions": {
    "UserCache": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "username": {
          "type": "string"
        },
        "testId": {
          "type": "string"
        },
        "testStartTime": {
          "type": "integer"
        },
        "currentLanguageIndex": {
          "type": "integer"
        },
        "body": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Body"
          }
        }
      },
      "required": [
        "body",
        "currentLanguageIndex",
        "testId",
        "testStartTime",
        "username"
      ],
      "title": "UserCache"
    },
    "Body": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "groupName": {
          "type": "string"
        },
        "active": {
          "type": "boolean"
        },
        "sections": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Section"
          }
        }
      },
      "required": ["active", "groupName", "sections"],
      "title": "Body"
    },
    "Section": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "sectionName": {
          "type": "string"
        },
        "maxQuestions": {
          "type": "integer"
        },
        "active": {
          "type": "boolean"
        },
        "questions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Question"
          }
        }
      },
      "required": ["active", "maxQuestions", "questions", "sectionName"],
      "title": "Section"
    },
    "Question": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "status": {
          "type": "integer"
        },
        "submit": {
          "type": ["null", "number"]
        },
        "timeSpent": {
          "type": "integer"
        },
        "lastAnswered": {
          "type": "integer"
        }
      },
      "required": ["id", "lastAnswered", "status", "submit", "timeSpent"],
      "title": "Question"
    }
  }
}

=== SuyashC1000/openmock/public/data/userCache.json
{
  "username": "John Doe",
  "testId": "t1234567890",
  "testStartTime": 1234567890,
  "currentLanguageIndex": 0,
  "body": [
    {
      "groupName": "Paper",
      "active": false,
      "sections": [
        {
          "sectionName": "General Aptitude",
          "maxQuestions": 0,
          "active": false,
          "questions": [
            {
              "id": "q123456789",
              "status": 0,
              "submit": null,
              "timeSpent": 0,
              "lastAnswered": 12345667890
            }
          ]
        }
      ]
    }
  ]
}
